#ifndef BARE_ADDON_ERRORS_H
#define BARE_ADDON_ERRORS_H

#define ERROR_GETTING_UV_LOOP         "ERROR_GETTING_UV_LOOP"
#define ERROR_INVALID_ARGUMENTS       "ERROR_INVALID_ARGUMENTS"
#define ERROR_CREATING_PROMISE        "ERROR_CREATING_PROMISE"
#define ERROR_NO_MEMORY               "ERROR_NO_MEMORY"
#define ERROR_OPEN_HANDLE_SCOPE       "ERROR_OPEN_HANDLE_SCOPE"
#define ERROR_RESOLVE_DEFERRED        "ERROR_RESOLVE_DEFERRED"
#define ERROR_CREATE_STRING_UTF8      "ERROR_CREATE_STRING_UTF8"
#define ERROR_CREATE_ERROR            "ERROR_CREATE_ERROR"
#define ERROR_UNKNOWN                 "ERROR_UNKNOWN"
#define ERROR_ARGUMENT_TYPE           "ERROR_ARGUMENT_TYPE"
#define ERROR_PORT_OUT_OF_RANGE       "ERROR_PORT_OUT_OF_RANGE"
#define ERROR_ARGUMENT_COUNT          "ERROR_ARGUMENT_COUNT"
#define ERROR_RESPONSE_TO_ARRAYBUFFER "ERROR_RESPONSE_TO_ARRAYBUFFER"

#endif // BARE_ADDON_ERRORS_H
